### ISSUE TITLE
Could you tell me the DGL version?  

### ISSUE THREAD

**Issue by PengJiazhen408** [TianyiChen0316/LOGER#1]
I install 1.0.2 following the instructions, but I encounter such bugs:

AttributeError: module 'dgl.function' has no attribute 'src_mul_edge'

AttributeError: module 'dgl.function' has no attribute 'copy_edge'

**Comment by TianyiChen0316** [comment]
The DGL version I use is 0.6.1. The GT module is copied from another project, and it uses some deprecated methods.

**Comment by PengJiazhen408** [comment]
Thank you very much for you patient answer!
