### ISSUE TITLE
How to reproduce the experiment?

### ISSUE THREAD

**Issue by a858438680** [TianyiChen0316/LOGER#2]
I'd like to know how to reproduce the Figure 6: Performance of LOGER on PostgreSQL in your paper.

Could you please tell me?

**Comment by TianyiChen0316** [comment]
You can use the following shell command to run the training process (taking TPC-DS in a database called `tpcds` as an example).

```shell
python train.py -F FILE_ID --dataset dataset/tpcds_train dataset/tpcds_test -D tpcds -U postgres
```

`-F` specifies the output file ID, which is related to the checkpoint file's path, testing outputs' path, etc. The results can be found in `results/{FILE_ID}.csv`, and further details can also be found there.

**Comment by a858438680** [comment]
Thank you very much for you patient answer!
